[snowflake]
user = "madhavrasal"
password = "Saama@123"
account = "uknsbnr-vr05941"
warehouse = "COMPUTE_WH"
database = "ADIDAS"
schema = "PUBLIC"

[connections.snowflake]
user = "madhavrasal"
password = "Saama@123"
account = "uknsbnr-vr05941"
warehouse = "COMPUTE_WH"
database = "ADIDAS"
schema = "PUBLIC"